import { Img, VOption } from "../ShowCars/data";

export const data: VOption[] = [
  {
    initName: "hybrid",
    imageSrc: Img("venza-side"),
    price: "39,900",
    mainName: "2021 Venza",
    firstPriceText: "32,570",
    est: "40/37",
    MPG: 70,
    MPGe: 0,
  },
  {
    initName: "",
    imageSrc: Img("c-hr-side"),
    price: "27,575",
    mainName: "2021 C-HR ",
    firstPriceText: "21,595",
    est: "27/31",
    MPG: 16,
    MPGe: 0,
  },
  {
    initName: "hybrid available",
    imageSrc: Img("rav4-side"),
    price: "34,780",
    mainName: "2021 RAV4",
    firstPriceText: "26,250",
    est: "28/35",
    MPG: 59,
    MPGe: 0,
  },
  {
    initName: "hybrid",
    imageSrc: Img("rav4hybrid-side"),
    price: "35,175",
    mainName: "2021 RAV4 Hybrid ",
    firstPriceText: "28,800",
    est: "41/38",
    MPG: 59,
    MPGe: 0,
  },
  {
    initName: "Plug-in Hybrid",
    imageSrc: Img(""),
    price: "47,760",
    mainName: "2021 RAV4 Prime",
    firstPriceText: "38,250",
    est: "38/94",
    MPG: 19,
    MPGe: 19,
  },

  // GET OTHER IMAGES
  //   {
  //     initName: "Hybrid available",
  //     imageSrc: Img(""),
  //     price: ",",
  //     mainName: "2021 ",
  //     firstPriceText: ",",
  //     est: "/",
  //     MPG:,
  //     MPGe: 0,
  //   },
  //   {
  //     initName: "",
  //     imageSrc: Img(""),
  //     price: ",",
  //     mainName: "2021 ",
  //     firstPriceText: ",",
  //     est: "/",
  //     MPG:,
  //     MPGe: 0,
  //   },
  //   {
  //     initName: "",
  //     imageSrc: Img(""),
  //     price: ",",
  //     mainName: "2021 ",
  //     firstPriceText: ",",
  //     est: "/",
  //     MPG:,
  //     MPGe: 0,
  //   },
  //   {
  //     initName: "",
  //     imageSrc: Img(""),
  //     price: ",",
  //     mainName: "2021 ",
  //     firstPriceText: ",",
  //     est: "/",
  //     MPG:,
  //     MPGe: 0,
  //   },
];
