import { VOption, Img } from "../ShowCars/data";

export const data: VOption[] = [
  {
    initName: "",
    imageSrc: Img("-side"),
    price: "",
    mainName: "",
    firstPriceText: "",
    est: "",
    MPG: 0,
    MPGe: 0,
  },
  {
    initName: "",
    imageSrc: Img("-side"),
    price: "",
    mainName: "",
    firstPriceText: "",
    est: "",
    MPG: 0,
    MPGe: 0,
  },
  {
    initName: "",
    imageSrc: Img("-side"),
    price: "",
    mainName: "",
    firstPriceText: "",
    est: "",
    MPG: 0,
    MPGe: 0,
  },
  {
    initName: "",
    imageSrc: Img("-side"),
    price: "",
    mainName: "",
    firstPriceText: "",
    est: "",
    MPG: 0,
    MPGe: 0,
  },
  {
    initName: "",
    imageSrc: Img("-side"),
    price: "",
    mainName: "",
    firstPriceText: "",
    est: "",
    MPG: 0,
    MPGe: 0,
  },
  {
    initName: "",
    imageSrc: Img("-side"),
    price: "",
    mainName: "",
    firstPriceText: "",
    est: "",
    MPG: 0,
    MPGe: 0,
  },
  {
    initName: "",
    imageSrc: Img("-side"),
    price: "",
    mainName: "",
    firstPriceText: "",
    est: "",
    MPG: 0,
    MPGe: 0,
  },
  {
    initName: "",
    imageSrc: Img("-side"),
    price: "",
    mainName: "",
    firstPriceText: "",
    est: "",
    MPG: 0,
    MPGe: 0,
  },
  {
    initName: "",
    imageSrc: Img("-side"),
    price: "",
    mainName: "",
    firstPriceText: "",
    est: "",
    MPG: 0,
    MPGe: 0,
  },
  {
    initName: "",
    imageSrc: Img("-side"),
    price: "",
    mainName: "",
    firstPriceText: "",
    est: "",
    MPG: 0,
    MPGe: 0,
  },
  {
    initName: "",
    imageSrc: Img("-side"),
    price: "",
    mainName: "",
    firstPriceText: "",
    est: "",
    MPG: 0,
    MPGe: 0,
  },
];
