import { Img, VOption } from "../ShowCars/data";

export const data: VOption[] = [
  {
    initName: "",
    imageSrc: Img("-side"),
    price: ",",
    mainName: "2021 ",
    firstPriceText: ",",
    est: "/",
    MPG: ,
    MPGe: 0,
    },
  {
    initName: "",
    imageSrc: Img("-side"),
    price: ",",
    mainName: "2021 ",
    firstPriceText: ",",
    est: "/",
    MPG: ,
    MPGe: 0,
    },
  {
    initName: "",
    imageSrc: Img("-side"),
    price: ",",
    mainName: "2021 ",
    firstPriceText: ",",
    est: "/",
    MPG: ,
    MPGe: 0,
    },
  {
    initName: "",
    imageSrc: Img("-side"),
    price: ",",
    mainName: "2021 ",
    firstPriceText: ",",
    est: "/",
    MPG: ,
    MPGe: 0,
    },
  {
    initName: "",
    imageSrc: Img("-side"),
    price: ",",
    mainName: "2021 ",
    firstPriceText: ",",
    est: "/",
    MPG: ,
    MPGe: 0,
    },
  {
    initName: "",
    imageSrc: Img("-side"),
    price: ",",
    mainName: "2021 ",
    firstPriceText: ",",
    est: "/",
    MPG: ,
    MPGe: 0,
    },
  {
    initName: "",
    imageSrc: Img("-side"),
    price: ",",
    mainName: "2021 ",
    firstPriceText: ",",
    est: "/",
    MPG: ,
    MPGe: 0,
    },
  {
    initName: "",
    imageSrc: Img("-side"),
    price: ",",
    mainName: "2021 ",
    firstPriceText: ",",
    est: "/",
    MPG: ,
    MPGe: 0,
    },
  {
    initName: "",
    imageSrc: Img("-side"),
    price: ",",
    mainName: "2021 ",
    firstPriceText: ",",
    est: "/",
    MPG: ,
    MPGe: 0,
    },
  {
    initName: "",
    imageSrc: Img("-side"),
    price: ",",
    mainName: "2021 ",
    firstPriceText: ",",
    est: "/",
    MPG: ,
    MPGe: 0,
    },
  {
    initName: "",
    imageSrc: Img("-side"),
    price: ",",
    mainName: "2021 ",
    firstPriceText: ",",
    est: "/",
    MPG: ,
    MPGe: 0,
    },
]