import { VOption, Img } from "../ShowCars/data";

export const data: VOption[] = [
  {
    initName: "",
    imageSrc: Img("uvp-gr-supra"),
    price: "",
    mainName: "GR Supra A91-CF Edition",
    firstPriceText: "",
    est: "",
    MPG: 0,
    MPGe: 0,
  },
  {
    initName: "",
    imageSrc: Img("uvp-corolla-cross"),
    price: "",
    mainName: "Corolla Cross",
    firstPriceText: "",
    est: "",
    MPG: 0,
    MPGe: 0,
  },
  {
    initName: "",
    imageSrc: Img("uvp-gr-86"),
    price: "",
    mainName: "GR 86",
    firstPriceText: "",
    est: "",
    MPG: 0,
    MPGe: 0,
  },
  {
    initName: "",
    imageSrc: Img("uvp-"),
    price: "",
    mainName: "Tacoma Trail Special Edition",
    firstPriceText: "",
    est: "",
    MPG: 0,
    MPGe: 0,
  },
  {
    initName: "",
    imageSrc: Img("uvp-"),
    price: "",
    mainName: "Tacoma TRD Pro",
    firstPriceText: "",
    est: "",
    MPG: 0,
    MPGe: 0,
  },
  {
    initName: "",
    imageSrc: Img("uvp-4runner-trdsport"),
    price: "",
    mainName: "4Runner TRD Sport",
    firstPriceText: "",
    est: "",
    MPG: 0,
    MPGe: 0,
  },
  {
    initName: "",
    imageSrc: Img("uvp-prius"),
    price: "",
    mainName: "Prius Nightshade Special Edition",
    firstPriceText: "",
    est: "",
    MPG: 0,
    MPGe: 0,
  },
  {
    initName: "",
    imageSrc: Img("uvp-highlander-hybrid-bronze-edition"),
    price: "",
    mainName: "Highlander Hybrid Bronze Edition",
    firstPriceText: "",
    est: "",
    MPG: 0,
    MPGe: 0,
  },
  {
    initName: "",
    imageSrc: Img("uvp-new-tundra"),
    price: "",
    mainName: "Tundra",
    firstPriceText: "",
    est: "",
    MPG: 0,
    MPGe: 0,
  },
  {
    initName: "",
    imageSrc: Img("uvp-bz4x-concept"),
    price: "",
    mainName: "Toyota bZ4X Concept",
    firstPriceText: "",
    est: "",
    MPG: 0,
    MPGe: 0,
  },
  {
    initName: "",
    imageSrc: Img("uvp-gr-hothatch"),
    price: "",
    mainName: "GR Hot HATCH",
    firstPriceText: "",
    est: "",
    MPG: 0,
    MPGe: 0,
  },
];
